USE db_users;

INSERT INTO professors (nombre_catedratico) VALUES ('ROGELIO ALFREDO SALAZAR DE LEON');
INSERT INTO professors (nombre_catedratico) VALUES ('EDUARDO MARTIN RIVERA PÉREZ');
INSERT INTO professors (nombre_catedratico) VALUES ('EDWIN JOSUE IXPATA REYES');
INSERT INTO professors (nombre_catedratico) VALUES ('INGRID MARISOL FLORES ESTRADA');
INSERT INTO professors (nombre_catedratico) VALUES ('CARLOS ENRIQUE GÓMEZ DONIS');
INSERT INTO professors (nombre_catedratico) VALUES ('DENNIS STANLEY BARRIOS GONZALEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('WILLIAM ESTUARDO ESCOBAR ARGUETA');
INSERT INTO professors (nombre_catedratico) VALUES ('CINTHYA PATRICIA ORTIZ QUIROA');
INSERT INTO professors (nombre_catedratico) VALUES ('JOSE RICARDO DE LEON SOLIS');
INSERT INTO professors (nombre_catedratico) VALUES ('KENNETH LUBECK CORADO ESQUIVEL');
INSERT INTO professors (nombre_catedratico) VALUES ('EDGAR YANUARIO LAJ HUN');
INSERT INTO professors (nombre_catedratico) VALUES ('ERICKA NATHALIE LOPEZ TORRES');
INSERT INTO professors (nombre_catedratico) VALUES ('CARLOS LEONEL MUÑOZ LEMUS');
INSERT INTO professors (nombre_catedratico) VALUES ('HELEN JEANNETH MARTÍNEZ SUM');
INSERT INTO professors (nombre_catedratico) VALUES ('SORAYA DEL ROSARIO MARTINEZ SUM');
INSERT INTO professors (nombre_catedratico) VALUES ('ILEANA GUISELA RALDA R. DE ILLESCAS');
INSERT INTO professors (nombre_catedratico) VALUES ('EVELYN CAROLINA MORALES RUIZ');
INSERT INTO professors (nombre_catedratico) VALUES ('ANA VELA CASTRO MELLADO');
INSERT INTO professors (nombre_catedratico) VALUES ('MONICA MARLENI QUIÑONEZ ANDRADE');
INSERT INTO professors (nombre_catedratico) VALUES ('CRISTOBAL MARDOQUEO ARRIOLA MAIREN');
INSERT INTO professors (nombre_catedratico) VALUES ('EDGAR HAROLDO TORRES SOTO');
INSERT INTO professors (nombre_catedratico) VALUES ('PEDRO RAFAEL MORAN ARAGON');
INSERT INTO professors (nombre_catedratico) VALUES ('MILDRED CATALINA HERNANDEZ ROLDAN');
INSERT INTO professors (nombre_catedratico) VALUES ('HILDA MYRIAM MÉNDEZ CASTILLO DE AVILA');
INSERT INTO professors (nombre_catedratico) VALUES ('OTTO LEONEL SUÁREZ MOTA');
INSERT INTO professors (nombre_catedratico) VALUES ('MIRIAM PATRICIA RUBIO CONTRERAS DE AKU');
INSERT INTO professors (nombre_catedratico) VALUES ('KARLA LIZBETH MARTÍNEZ VARGAS');
INSERT INTO professors (nombre_catedratico) VALUES ('ERWIN DANILO GONZALEZ TREJO');
INSERT INTO professors (nombre_catedratico) VALUES ('PABLO ENRIQUE MORALES PANIAGUA');
INSERT INTO professors (nombre_catedratico) VALUES ('MARILYN CARIBEL ROJAS MALDONADO');
INSERT INTO professors (nombre_catedratico) VALUES ('GERARDO ORDONEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('DAVID SAMUEL FIORINI MORALES');
INSERT INTO professors (nombre_catedratico) VALUES ('JAIME DOMINGO CARRANZA GONZALEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('ALAN GIOVANI COSILLO PINTO');
INSERT INTO professors (nombre_catedratico) VALUES ('MARIO ENRIQUE RIVERA GONZALEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('NOEL JOEL GRAMAJO MONTERROSO');
INSERT INTO professors (nombre_catedratico) VALUES ('WALTER ARNOLDO BARDALES ESPINOZA');
INSERT INTO professors (nombre_catedratico) VALUES ('JUAN ALBERTO ORTIZ ESTURBAN');
INSERT INTO professors (nombre_catedratico) VALUES ('ALLEN EDUARDO RAMIREZ TOLEDO');
INSERT INTO professors (nombre_catedratico) VALUES ('ANDREA SUSANA LÓPEZ RAMÍREZ');
INSERT INTO professors (nombre_catedratico) VALUES ('ESDRAS FELICIANO MIRANDA OROZCO');
INSERT INTO professors (nombre_catedratico) VALUES ('NICOLAS DE JESUS GUZMAN SAENZ');
INSERT INTO professors (nombre_catedratico) VALUES ('BRYAN ALEJANDRO CASTAÑON MARTINEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('FERNANDO AMILCAR BOITON VELASQUEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('JORGE ALEJANDRO AREVALO VALDEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('HERMAN IGOR VELIZ LINARES');
INSERT INTO professors (nombre_catedratico) VALUES ('JURGEN ANDONI RAMIREZ RAMÍREZ');
INSERT INTO professors (nombre_catedratico) VALUES ('JOSE ANIBAL SILVA DE LOS ANGELES');
INSERT INTO professors (nombre_catedratico) VALUES ('RAMON BENJAMIN PIEDRASANTA BATZ');
INSERT INTO professors (nombre_catedratico) VALUES ('SHARONN PRYSCILA PU MORALES');
INSERT INTO professors (nombre_catedratico) VALUES ('MARIO RENE DE LEON GARCIA');
INSERT INTO professors (nombre_catedratico) VALUES ('RENATO GIOVANNI PONCIANO SANDOVAL');
INSERT INTO professors (nombre_catedratico) VALUES ('GUSTAVO ADOLFO SANTOS OROZCO');
INSERT INTO professors (nombre_catedratico) VALUES ('ALEJANDRO ESTRADA MARTINEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('ERICKA JOHANA CANO DIAZ');
INSERT INTO professors (nombre_catedratico) VALUES ('JOSE ALBERTO BOY PIEDRASANTA');
INSERT INTO professors (nombre_catedratico) VALUES ('FRANCISCO BERNARDO R DE LA ROSA');
INSERT INTO professors (nombre_catedratico) VALUES ('LUIS CARLOS BOLANOS MENDEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('MAYRA VIRGINIA CASTILLO MONTES');
INSERT INTO professors (nombre_catedratico) VALUES ('OSCAR ALBERTO MARTINEZ LOBOS');
INSERT INTO professors (nombre_catedratico) VALUES ('EDER KEITH PAZ TIGUILA');
INSERT INTO professors (nombre_catedratico) VALUES ('CESAR LEONEL OVALLE RODRIGUEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('ERICK GEOVANI AGUSTIN MARROQUIN');
INSERT INTO professors (nombre_catedratico) VALUES ('GLENDA PATRICIA GARCIA SORIA');
INSERT INTO professors (nombre_catedratico) VALUES ('JOSE MARIA SAQUIMUX CANASTUJ');
INSERT INTO professors (nombre_catedratico) VALUES ('CARLOS ALFREDO ANGULO HUERGO');
INSERT INTO professors (nombre_catedratico) VALUES ('HELEN ROCIO RAMIREZ LUCAS');
INSERT INTO professors (nombre_catedratico) VALUES ('CARLOS AUGUSTO MORALES SANTACRUZ');
INSERT INTO professors (nombre_catedratico) VALUES ('SILVIA PATRICIA HURTARTE HERNANDEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('OSWALDO ROMEO ESCOBAR ALVAREZ');
INSERT INTO professors (nombre_catedratico) VALUES ('ARTURO RODRIGO SAMAYOA DARDON');
INSERT INTO professors (nombre_catedratico) VALUES ('CESAR ARIEL VILLELA RODAS');
INSERT INTO professors (nombre_catedratico) VALUES ('ANGEL ROBERTO SIC GARCIA');
INSERT INTO professors (nombre_catedratico) VALUES ('DOUGLAS KENEDY ROMAN AVILA');
INSERT INTO professors (nombre_catedratico) VALUES ('NERY AMILCAR MEJIA GODINEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('AMAHAN SANCHEZ ALVAREZ');
INSERT INTO professors (nombre_catedratico) VALUES ('OSCAR HUMBERTO MONTES ESTRADA');
INSERT INTO professors (nombre_catedratico) VALUES ('CARLOS ALBERTO GARRIDO LOPEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('SILVIA CAROLINA LEMUS CASTRO');
INSERT INTO professors (nombre_catedratico) VALUES ('FRANCISCO JAVIER GARCIA FLORES');
INSERT INTO professors (nombre_catedratico) VALUES ('RENALDO GIRON ALVARADO');
INSERT INTO professors (nombre_catedratico) VALUES ('PABLO RODOLFO ZUÑIGA RAMIREZ');
INSERT INTO professors (nombre_catedratico) VALUES ('JOSE ALFREDO GONZALEZ DIAZ');
INSERT INTO professors (nombre_catedratico) VALUES ('MARIO GUSTAVO LOPEZ HERNANDEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('JOSE ALFONSO VELASQUEZ DIAZ');
INSERT INTO professors (nombre_catedratico) VALUES ('JUAN ORLANDO LOPEZ OROZCO');
INSERT INTO professors (nombre_catedratico) VALUES ('OTTO MIGUEL HURTARTE HERNANDEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('RODOLFO ESTUARDO QUIROA MELENDRES');
INSERT INTO professors (nombre_catedratico) VALUES ('JOSE ADOLFO TUNA AGUILAR');
INSERT INTO professors (nombre_catedratico) VALUES ('EDDY JOSUE SOLARES ESPINOZA');
INSERT INTO professors (nombre_catedratico) VALUES ('RONAL NOE GALVEZ GARCIA');
INSERT INTO professors (nombre_catedratico) VALUES ('ANGELICA BECILIA PACHECO MAZARIEGOS');
INSERT INTO professors (nombre_catedratico) VALUES ('PAMELA CRISTINA SIKAHALL URIZAR');
INSERT INTO professors (nombre_catedratico) VALUES ('BAYRON ARMANDO CUYAN CULAJAY');
INSERT INTO professors (nombre_catedratico) VALUES ('LUIS ADOLFO DE LEON GOMEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('JORGE GILBERTO GONZALEZ PADILLA');
INSERT INTO professors (nombre_catedratico) VALUES ('ERIC JOSUE JACOBS MAZARIEGOS');
INSERT INTO professors (nombre_catedratico) VALUES ('BRIAN ENRIQUE CHICOL MORALES');
INSERT INTO professors (nombre_catedratico) VALUES ('LUIS ALBERTO BAUTISTA');
INSERT INTO professors (nombre_catedratico) VALUES ('CARLOS RODOLFO MARTINEZ GIRON');
INSERT INTO professors (nombre_catedratico) VALUES ('ERIK LEONEL GARCIA SANTANA');
INSERT INTO professors (nombre_catedratico) VALUES ('CARLOS ANTONIO CAJAS VIDAURRE');
INSERT INTO professors (nombre_catedratico) VALUES ('WALTER GIOVANNI ALVAREZ MARROQUIN');
INSERT INTO professors (nombre_catedratico) VALUES ('CLAUDIA CECILIA CONTRERAS FOLGAR DE ALFARO');
INSERT INTO professors (nombre_catedratico) VALUES ('EDGAR DARIO ALVAREZ COTI');
INSERT INTO professors (nombre_catedratico) VALUES ('MARIO RENATO ESCOBEDO MARTINEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('ERICK ESTUARDO HERNANDEZ GARCIA');
INSERT INTO professors (nombre_catedratico) VALUES ('RICARDO ENRIQUE CONTRERAS FOLGAR');
INSERT INTO professors (nombre_catedratico) VALUES ('CESAR ABIGAIL GARCIA NAJERA');
INSERT INTO professors (nombre_catedratico) VALUES ('CALIXTO SANTIAGO MONTEAGUDO CORDERO');
INSERT INTO professors (nombre_catedratico) VALUES ('MURPHY OLYMPO PAIZ RECINOS');
INSERT INTO professors (nombre_catedratico) VALUES ('PABLO CESAR ANÍBAL SARAVIA SOLARES');
INSERT INTO professors (nombre_catedratico) VALUES ('JORGE MARIO ESTRADA ASTURIAS');
INSERT INTO professors (nombre_catedratico) VALUES ('FRANCISCO JAVIER GONZALEZ LOPEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('GUILLERMO ANTONIO PUENTE ROMERO');
INSERT INTO professors (nombre_catedratico) VALUES ('JULIO ROLANDO BARRIOS ARCHILA');
INSERT INTO professors (nombre_catedratico) VALUES ('OTTO FERNANDO ANDRINO GONZALEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('ARMANDO ALONSO RIVERA CARRILLO');
INSERT INTO professors (nombre_catedratico) VALUES ('INGRID SALOME RODRIGUEZ DE LOUKOTA');
INSERT INTO professors (nombre_catedratico) VALUES ('MARIO ALBERTO REYES CALDERÓN');
INSERT INTO professors (nombre_catedratico) VALUES ('GUSTAVO BENIGNO OROZCO GODINEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('ANA MARÍA NAVARRO OROZCO');
INSERT INTO professors (nombre_catedratico) VALUES ('ARMANDO GALVEZ CASTILLO');
INSERT INTO professors (nombre_catedratico) VALUES ('VÍCTOR RENÉ PÉREZ MAYÉN');
INSERT INTO professors (nombre_catedratico) VALUES ('HELMUNT FEDERICO CHICOL CABRERA');
INSERT INTO professors (nombre_catedratico) VALUES ('ENDOR STEVE ORTIZ DEL CID');
INSERT INTO professors (nombre_catedratico) VALUES ('DANIEL DE JESUS VASQUEZ AGUILAR');
INSERT INTO professors (nombre_catedratico) VALUES ('FERNANDO ALFREDO MOSCOSO LIRA');
INSERT INTO professors (nombre_catedratico) VALUES ('JOSE GUILLERMO BEDOYA BARRIOS');
INSERT INTO professors (nombre_catedratico) VALUES ('SAUL CABEZAS DURAN');
INSERT INTO professors (nombre_catedratico) VALUES ('JULIO ANDRÉS GAITÁN ALVAREZ');
INSERT INTO professors (nombre_catedratico) VALUES ('JORGE LUIS PEREZ RIVERA');
INSERT INTO professors (nombre_catedratico) VALUES ('SERGIO LEONEL GOMEZ BRAVO');
INSERT INTO professors (nombre_catedratico) VALUES ('HECTOR FRANCISCO REYES FRANCO');
INSERT INTO professors (nombre_catedratico) VALUES ('JUAN CARLOS CORDOVA ZECEÑA');
INSERT INTO professors (nombre_catedratico) VALUES ('NESTOR OBDULIO ALEJANDRO CHAMALE CHITIC');
INSERT INTO professors (nombre_catedratico) VALUES ('WENDY NORA MIRANDA LOPEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('HUGO LEONEL TIUL VALENZUELA');
INSERT INTO professors (nombre_catedratico) VALUES ('LUIS EDUARDO DURAN CORDOVA');
INSERT INTO professors (nombre_catedratico) VALUES ('JULIO CESAR SOLARES PENATE');
INSERT INTO professors (nombre_catedratico) VALUES ('CARLOS EDUARDO GUZMAN SALAZAR');
INSERT INTO professors (nombre_catedratico) VALUES ('RONY DANIEL HERNANDEZ GOMEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('RAFAEL ENRIQUE MORALES OCHOA');
INSERT INTO professors (nombre_catedratico) VALUES ('DENNIS SALVADOR ARGUETA MAYORGA');
INSERT INTO professors (nombre_catedratico) VALUES ('LUIS EDUARDO PORTILLO ESPAÑA');
INSERT INTO professors (nombre_catedratico) VALUES ('BENITO ANTONIO BACA MÈNDEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('LESBIA MAGALI HERRERA LOPEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('CLAUDIO CESAR CASTAÑON CONTRERAS');
INSERT INTO professors (nombre_catedratico) VALUES ('KARLA GIOVANNA JUDITH PÉREZ LOARCA');
INSERT INTO professors (nombre_catedratico) VALUES ('MYNOR RODERICO FIGUEROA FUENTES');
INSERT INTO professors (nombre_catedratico) VALUES ('ROBERTO GUZMAN ORTIZ');
INSERT INTO professors (nombre_catedratico) VALUES ('JOSE FERNANDO SAMAYOA ROLDAN');
INSERT INTO professors (nombre_catedratico) VALUES ('PEDRO ANTONIO AGUILAR POLANCO');
INSERT INTO professors (nombre_catedratico) VALUES ('NORMAN LEONEL SIGUI GIL');
INSERT INTO professors (nombre_catedratico) VALUES ('JESUS ALBERTO GUZMAN POLANCO');
INSERT INTO professors (nombre_catedratico) VALUES ('GUILLERMO FRANCISCO MELINI SALGUERO');
INSERT INTO professors (nombre_catedratico) VALUES ('WILLIAM SAMUEL GUEVARA ORELLANA');
INSERT INTO professors (nombre_catedratico) VALUES ('EDGAR FRANCISCO RODAS ROBLEDO');
INSERT INTO professors (nombre_catedratico) VALUES ('WALTER ROLANDO SALAZAR GONZÁLEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('HUGO LEONEL MONTENEGRO FRANCO');
INSERT INTO professors (nombre_catedratico) VALUES ('JOSÉ ESTUARDO GALINDO ESCOBAR');
INSERT INTO professors (nombre_catedratico) VALUES ('YEFRY VALENTIN ROSALES JUAREZ');
INSERT INTO professors (nombre_catedratico) VALUES ('MARIO RODOLFO CORZO AVILA');
INSERT INTO professors (nombre_catedratico) VALUES ('LUIS ESTUARDO SARAVIA RAMIREZ');
INSERT INTO professors (nombre_catedratico) VALUES ('OMAR ENRIQUE MEDRANO MENDEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('VICTOR VINICIO BARRIOS US');
INSERT INTO professors (nombre_catedratico) VALUES ('OMAR GILBERTO FLORES BELTETON');
INSERT INTO professors (nombre_catedratico) VALUES ('OSWALDO JOSE OROZCO AREAS');
INSERT INTO professors (nombre_catedratico) VALUES ('BERTHA ROXANDA MOLINA LEON DE QUINTO');
INSERT INTO professors (nombre_catedratico) VALUES ('CASTA PETRONA ZECENA ZECENA');
INSERT INTO professors (nombre_catedratico) VALUES ('EDGAR GAMALIEL DE LEON HERNANDEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('TANNIA MAGALY DE LEON MORAN');
INSERT INTO professors (nombre_catedratico) VALUES ('GABRIEL ESTUARDO SOLÓRZANO CASTELLANOS');
INSERT INTO professors (nombre_catedratico) VALUES ('TELMA MARICELA CANO MORALES');
INSERT INTO professors (nombre_catedratico) VALUES ('BYRON RENE AGUILAR UCK');
INSERT INTO professors (nombre_catedratico) VALUES ('ADELA MARIA MARROQUIN GONZALEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('FRANCISCO ABEN ROSALES CEREZO');
INSERT INTO professors (nombre_catedratico) VALUES ('MERCEDES ESTHER ROQUEL CHAVEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('EMMETT ECHEVERRIA VALENZUELA');
INSERT INTO professors (nombre_catedratico) VALUES ('JULIO RICARDO DIAZ PAPPA');
INSERT INTO professors (nombre_catedratico) VALUES ('CESAR ALFONSO GARCIA GUERRA');
INSERT INTO professors (nombre_catedratico) VALUES ('ERWIN MANUEL ORTIZ CASTILLO');
INSERT INTO professors (nombre_catedratico) VALUES ('GERSON JOÉL ORTEGA MORALES');
INSERT INTO professors (nombre_catedratico) VALUES ('VICTOR MANUEL MONZON VALDEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('INGRID LORENA BENITEZ PACHECO');
INSERT INTO professors (nombre_catedratico) VALUES ('RAMIRO AUGUSTO SANTIZO GONZALEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('ANA RUFINA HERRERA SOTO');
INSERT INTO professors (nombre_catedratico) VALUES ('WILLIAM EDUARDO FAGIANI CRUZ');
INSERT INTO professors (nombre_catedratico) VALUES ('JULIO DAVID VARGAS GARCIA');
INSERT INTO professors (nombre_catedratico) VALUES ('FREDY MAURICIO MONROY PERALTA');
INSERT INTO professors (nombre_catedratico) VALUES ('LUIS ALFREDO ASTURIAS ZUNIGA');
INSERT INTO professors (nombre_catedratico) VALUES ('ADOLFO NARCISO GRAMAJO ANTONIO');
INSERT INTO professors (nombre_catedratico) VALUES ('ANA GLORIA MONTES PEÑA');
INSERT INTO professors (nombre_catedratico) VALUES ('ORLANDO POSADAS VALDEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('SERGIO ALEJANDRO RECINOS');
INSERT INTO professors (nombre_catedratico) VALUES ('JORGE EMILIO GODINEZ LEMUS');
INSERT INTO professors (nombre_catedratico) VALUES ('WILLIAMS GUILLERMO ALVAREZ MEJIA');
INSERT INTO professors (nombre_catedratico) VALUES ('KAREN NOELIA HERNÁNDEZ AVILA');
INSERT INTO professors (nombre_catedratico) VALUES ('DINNA LISSETTE ESTRADA MOREIRA DE ROSSAL');
INSERT INTO professors (nombre_catedratico) VALUES ('MARIO JOSE MERIDA MERE');
INSERT INTO professors (nombre_catedratico) VALUES ('MANUEL GILBERTO GALVAN ESTRADA');
INSERT INTO professors (nombre_catedratico) VALUES ('CARLOS SALVADOR WONG DAVI');
INSERT INTO professors (nombre_catedratico) VALUES ('HILDA PIEDAD PALMA RAMOS');
INSERT INTO professors (nombre_catedratico) VALUES ('CARLA DEYANIRA GORDILLO DE MARCHENA');
INSERT INTO professors (nombre_catedratico) VALUES ('AURELIA ANABELA CORDOVA ESTRADA');
INSERT INTO professors (nombre_catedratico) VALUES ('RIGOBERTO RAFAEL SANDOVAL LOPEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('MILTON ALEXANDER FUENTES OROZCO');
INSERT INTO professors (nombre_catedratico) VALUES ('CARLOS SNELL CHICOL MORALES');
INSERT INTO professors (nombre_catedratico) VALUES ('MILTON LENIN HERNANDEZ GONZALEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('JOSE GABRIEL ORDONEZ MORALES');
INSERT INTO professors (nombre_catedratico) VALUES ('HERBERT SAMUEL FIGUEROA AVENDAÑO');
INSERT INTO professors (nombre_catedratico) VALUES ('HUGO LEONEL RAMIREZ ORTIZ');
INSERT INTO professors (nombre_catedratico) VALUES ('WUILLIAN RICARDO YON CHAVARRIA');
INSERT INTO professors (nombre_catedratico) VALUES ('MARÍA LORENA RIZZO LÓPEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('BYRON GIOVANNI PALACIOS COLINDRES');
INSERT INTO professors (nombre_catedratico) VALUES ('CARLOS ANIBAL CHICOJAY COLOMA');
INSERT INTO professors (nombre_catedratico) VALUES ('CARLOS ENRIQUE CHICOL CABRERA');
INSERT INTO professors (nombre_catedratico) VALUES ('LUIS EDUARDO CORONADO NOJ');
INSERT INTO professors (nombre_catedratico) VALUES ('MARIO ESTUARDO ARRIOLA AVILA');
INSERT INTO professors (nombre_catedratico) VALUES ('ESTUARDO JEREZ SANTOS');
INSERT INTO professors (nombre_catedratico) VALUES ('VICTOR MANUEL AVILA SARMIENTO');
INSERT INTO professors (nombre_catedratico) VALUES ('NORA LEONOR GARCIA TOBAR');
INSERT INTO professors (nombre_catedratico) VALUES ('FRANCISCO ARTURO HERNANDEZ ARRIAZA');
INSERT INTO professors (nombre_catedratico) VALUES ('JULIO CÉSAR VILLATORO SANABRIA');
INSERT INTO professors (nombre_catedratico) VALUES ('JUAN CARLOS JEREZ JUAREZ');
INSERT INTO professors (nombre_catedratico) VALUES ('SELVIN ESTUARDO JOACHIN JUAREZ');
INSERT INTO professors (nombre_catedratico) VALUES ('JULIO OSWALDO ROJAS ARGUETA');
INSERT INTO professors (nombre_catedratico) VALUES ('HUGO LEONEL ALVARADO DE LEON');
INSERT INTO professors (nombre_catedratico) VALUES ('RENATO ISAAC RIVERA PEREZ');
INSERT INTO professors (nombre_catedratico) VALUES ('YESSENIA JANIRA MARROQUÍN MARTÍNEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('ALBERTO EULALIO HERNANDEZ GARCIA');
INSERT INTO professors (nombre_catedratico) VALUES ('JOSE ROLANDO CHAVEZ SALAZAR');
INSERT INTO professors (nombre_catedratico) VALUES ('LIDIA VALENTINA JÁCOME CUCÚ');
INSERT INTO professors (nombre_catedratico) VALUES ('OSMAR BERNAL GODINEZ VELÁSQUEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('MARIA MARTHA WOLFORD E. DE HERNANDEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('JOSE LUIS ANTONIO VALDEAVELLANO ARDON');
INSERT INTO professors (nombre_catedratico) VALUES ('JAVIER ANTONIO CERÓN ROSALES');
INSERT INTO professors (nombre_catedratico) VALUES ('ROCIO CAROLINA MEDINA GALINDO');
INSERT INTO professors (nombre_catedratico) VALUES ('LAURA ROSMERY BRIONES ZELADA');
INSERT INTO professors (nombre_catedratico) VALUES ('YOCASTA IVANOBLA ORTIZ DEL CID');
INSERT INTO professors (nombre_catedratico) VALUES ('FLOR DE MAYO GONZALEZ MIRANDA');
INSERT INTO professors (nombre_catedratico) VALUES ('ELMER DIONICIO SUC CHOCOOJ');
INSERT INTO professors (nombre_catedratico) VALUES ('JAIME ROBERTO RUIZ DIAZ');
INSERT INTO professors (nombre_catedratico) VALUES ('ALDO OZAETA SANTIAGO');
INSERT INTO professors (nombre_catedratico) VALUES ('MAYRA SAADETH ARREAZA MARTINEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('JOSE ANTONIO CAMBARA GODOY');
INSERT INTO professors (nombre_catedratico) VALUES ('BYRON GERARDO CHOCOOJ BARRIENTOS');
INSERT INTO professors (nombre_catedratico) VALUES ('KAREN NATALIE MEINICKE PALACIOS');
INSERT INTO professors (nombre_catedratico) VALUES ('CESAR ERNESTO URQUIZU RODAS');
INSERT INTO professors (nombre_catedratico) VALUES ('ISMAEL HOMERO JEREZ GONZALEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('OSCAR APARICIO SEGURA MONZON');
INSERT INTO professors (nombre_catedratico) VALUES ('VICTOR HUGO GARCIA ROQUE');
INSERT INTO professors (nombre_catedratico) VALUES ('NANCY MARIA GUTIERREZ SAMAYOA');
INSERT INTO professors (nombre_catedratico) VALUES ('MARIA ALEJANDRA MA VILLATORO');
INSERT INTO professors (nombre_catedratico) VALUES ('ALEX EVELIO CASTAÑEDA SALAZAR');
INSERT INTO professors (nombre_catedratico) VALUES ('GUIPPSY JEANNIRA MENENDEZ PEREZ');
INSERT INTO professors (nombre_catedratico) VALUES ('JULIO ROBERTO LUNA AROCHE');
INSERT INTO professors (nombre_catedratico) VALUES ('ALBA MARITZA GUERRERO SPINOLA');
INSERT INTO professors (nombre_catedratico) VALUES ('ERIC RONALDO RUIZ MATIAS');
INSERT INTO professors (nombre_catedratico) VALUES ('JOSÉ MANUEL MORO BLANCO');
INSERT INTO professors (nombre_catedratico) VALUES ('JOSE ANTONIO GRACIAS GONZALEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('JORGE RODOLFO GARCIA CARRERA');
INSERT INTO professors (nombre_catedratico) VALUES ('ALEJANDRO CASTAÑON LOPEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('SURIEL CRISTINA ABALLI HERWING');
INSERT INTO professors (nombre_catedratico) VALUES ('MIGUEL ANGEL CANCINOS RENDON');
INSERT INTO professors (nombre_catedratico) VALUES ('CESAR AUGUSTO FERNANDEZ CACERES');
INSERT INTO professors (nombre_catedratico) VALUES ('JORGE LUIS ALVAREZ MEJIA');
INSERT INTO professors (nombre_catedratico) VALUES ('EDWIN ADALBERTO BRACAMONTE OROZCO');
INSERT INTO professors (nombre_catedratico) VALUES ('LADY MARIEBELIA ELIAS ESTRADA');
INSERT INTO professors (nombre_catedratico) VALUES ('LESBIA CAROLINA CARRANZA ESCOBAR');
INSERT INTO professors (nombre_catedratico) VALUES ('KAREN LUCRECIA HURTARTE PINEDA');
INSERT INTO professors (nombre_catedratico) VALUES ('ANGELICA DEL CARMEN PILO POZ');
INSERT INTO professors (nombre_catedratico) VALUES ('LUIS MANFREDO REYES CHAVEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('JONATHAN EFREN ALVAREZ CACACHO');
INSERT INTO professors (nombre_catedratico) VALUES ('MAYRA VIRGINIA CARVAJAL CASTILLO');
INSERT INTO professors (nombre_catedratico) VALUES ('MARIA EUGENIA AGUILAR BOBADILLA');
INSERT INTO professors (nombre_catedratico) VALUES ('CARLOS GUSTAVO ALONZO');
INSERT INTO professors (nombre_catedratico) VALUES ('MANUEL HAROLDO CASTILLO REYNA');
INSERT INTO professors (nombre_catedratico) VALUES ('MOISES EDUARDO VELASQUEZ OLIVA');
INSERT INTO professors (nombre_catedratico) VALUES ('NEFTALI DE JESUS CALDERON MENDEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('MARLON ANTONIO PEREZ TURK');
INSERT INTO professors (nombre_catedratico) VALUES ('CLAUDIA LICETH ROJAS MORALES');
INSERT INTO professors (nombre_catedratico) VALUES ('JOSE MANUEL RUIZ JUAREZ');
INSERT INTO professors (nombre_catedratico) VALUES ('EDWIN ESTUARDO ZAPETA GOMEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('FERNANDO JOSÉ PAZ GONZÁLEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('EDGAR RENE ORNELIS HOIL');
INSERT INTO professors (nombre_catedratico) VALUES ('ALVARO OBRAYAN HERNÁNDEZ GARCÍA');
INSERT INTO professors (nombre_catedratico) VALUES ('LUIS FERNANDO ESPINO BARRIOS');
INSERT INTO professors (nombre_catedratico) VALUES ('JUAN ALVARO DIAZ ARDAVIN');
INSERT INTO professors (nombre_catedratico) VALUES ('OSCAR ALEJANDRO PAZ CAMPOS');
INSERT INTO professors (nombre_catedratico) VALUES ('ÁLVARO GIOVANNI LONGO MORALES');
INSERT INTO professors (nombre_catedratico) VALUES ('OTTO AMILCAR RODRIGUEZ ACOSTA');
INSERT INTO professors (nombre_catedratico) VALUES ('LUIS ALBERTO ARIAS SOLÓRZANO');
INSERT INTO professors (nombre_catedratico) VALUES ('KEVIN ADIEL LAJPOP AJPACAJA');
INSERT INTO professors (nombre_catedratico) VALUES ('MARIO JOSE BAUTISTA FUENTES');
INSERT INTO professors (nombre_catedratico) VALUES ('OTTO RENE ESCOBAR LEIVA');
INSERT INTO professors (nombre_catedratico) VALUES ('GABRIEL ALEJANDRO DIAZ LOPEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('EVEREST DARWIN MEDINILLA RODRIGUEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('MARCO TULIO ALDANA PRILLWITZ');
INSERT INTO professors (nombre_catedratico) VALUES ('BAYRON WOSVELY LOPEZ LOPEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('EDGAR RUBEN SABAN RAXON');
INSERT INTO professors (nombre_catedratico) VALUES ('MIRNA IVONNE ALDANA LARRAZABAL');
INSERT INTO professors (nombre_catedratico) VALUES ('LUIS ALBERTO VETTORAZZI ESPANA');
INSERT INTO professors (nombre_catedratico) VALUES ('VIRGINIA VICTORIA TALA AYERDI');
INSERT INTO professors (nombre_catedratico) VALUES ('FLORIZA FELIPA AVILA PESQUERA DE MEDINILLA');
INSERT INTO professors (nombre_catedratico) VALUES ('VIVIAN DAMARIS CAMPOS GONZALEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('DAVID ESTUARDO MORALES AJCOT');
INSERT INTO professors (nombre_catedratico) VALUES ('ZULMA KARINA AGUIRRE ORDONEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('MANUEL FERNANDO LOPEZ FERNANDEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('CARLOS ALFREDO AZURDIA MORALES');
INSERT INTO professors (nombre_catedratico) VALUES ('EDGAR ESTUARDO SANTOS SUTUJ');
INSERT INTO professors (nombre_catedratico) VALUES ('PEDRO PABLO HERNANDEZ RAMIREZ');
INSERT INTO professors (nombre_catedratico) VALUES ('ALLAN ALBERTO MORATAYA GÓMEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('WALTER JACOBO GALICIA GARCIA');
INSERT INTO professors (nombre_catedratico) VALUES ('JORGE LUIS PALACIOS PINTO');
INSERT INTO professors (nombre_catedratico) VALUES ('PABLO RENÉ LEÓN MARQUEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('ANA PAOLA MÉNDEZ DE LEÓN');
INSERT INTO professors (nombre_catedratico) VALUES ('JORGE MARCELO IXQUIAC CABRERA');
INSERT INTO professors (nombre_catedratico) VALUES ('BRENDA IZABEL MIRANDA CONSUEGRA');
INSERT INTO professors (nombre_catedratico) VALUES ('ESTUARDO AUGUSTO GARRIDO CHINCHILLA');
INSERT INTO professors (nombre_catedratico) VALUES ('CARLOS ALBERTO ARIAS LARA');
INSERT INTO professors (nombre_catedratico) VALUES ('ANDRES MANUEL REMIS SALGUERO');
INSERT INTO professors (nombre_catedratico) VALUES ('LIGIA EUNICE VASQUEZ DARDON');
INSERT INTO professors (nombre_catedratico) VALUES ('GREYSI ILDOARA CALDERON CHAY');
INSERT INTO professors (nombre_catedratico) VALUES ('JOSE MARIANO GATICA HUERTAS');
INSERT INTO professors (nombre_catedratico) VALUES ('CARLOS MATIAS CASTELLANOS ARGUIJO');
INSERT INTO professors (nombre_catedratico) VALUES ('CHRISTA DEL ROSARIO CLASSON REHWOLDT DE PINTO');
INSERT INTO professors (nombre_catedratico) VALUES ('JUAN MERCK COS');
INSERT INTO professors (nombre_catedratico) VALUES ('LUIS GREGORIO ALFARO VELIZ');
INSERT INTO professors (nombre_catedratico) VALUES ('MAYRA REBECA GARCIA SORIA DE SIERRA');
INSERT INTO professors (nombre_catedratico) VALUES ('OSCAR ARGUETA HERNANDEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('SILVIO JOSE RODRIGUEZ SERRANO');
INSERT INTO professors (nombre_catedratico) VALUES ('DIEGO ISRAEL NAVARRO GODINEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('EDWIN ESTUARDO SARCEÑO ZEPEDA');
INSERT INTO professors (nombre_catedratico) VALUES ('EMILIO VLADIMIR LUX MONROY');
INSERT INTO professors (nombre_catedratico) VALUES ('SIGRID ALITZA CALDERON DE LEON');
INSERT INTO professors (nombre_catedratico) VALUES ('NORMA ILEANA SARMIENTO ZECENA');
INSERT INTO professors (nombre_catedratico) VALUES ('SINDY MASSIEL GODINEZ BAUTISTA');
INSERT INTO professors (nombre_catedratico) VALUES ('JAIME HUMBERTO BATTEN ESQUIVEL');
INSERT INTO professors (nombre_catedratico) VALUES ('KENNETH ISSUR ESTRADA RUIZ');
INSERT INTO professors (nombre_catedratico) VALUES ('MANUEL ALFREDO ARRIVILLAGA OCHAETA');
INSERT INTO professors (nombre_catedratico) VALUES ('LORENA VICTORIA PINEDA CABRERA');
INSERT INTO professors (nombre_catedratico) VALUES ('NATANAEL JONATHAN REQUENA GOMEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('DIANA ORALIA SALGUERO ESPANA');
INSERT INTO professors (nombre_catedratico) VALUES ('EDWIN JOSÉ SARAVIA CANO');
INSERT INTO professors (nombre_catedratico) VALUES ('ALEX SUNTECUN CASTELLANOS');
INSERT INTO professors (nombre_catedratico) VALUES ('JUAN CARLOS LINARES CRUZ');
INSERT INTO professors (nombre_catedratico) VALUES ('CARLOS HUMBERTO PEREZ RODRIGUEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('LUIS FELIPE PEREZ URIAS');
INSERT INTO professors (nombre_catedratico) VALUES ('WENDY MARISOL OROZCO MIRANDA');
INSERT INTO professors (nombre_catedratico) VALUES ('TONY YOBANY BARRERA DONIS');
INSERT INTO professors (nombre_catedratico) VALUES ('HUGO ARMANDO POLANCO VASQUEZ');
INSERT INTO professors (nombre_catedratico) VALUES ('EVELYN ELVIRA GUALÍM SANCHEZ');

DELIMITER //
CREATE FUNCTION get_random_credito() 
RETURNS INT
DETERMINISTIC
NO SQL
BEGIN
    RETURN FLOOR(1 + (RAND() * 6));
END//
DELIMITER ;

DELIMITER //
CREATE TRIGGER before_insert_courses
BEFORE INSERT ON courses
FOR EACH ROW
BEGIN
    SET NEW.creditos = get_random_credito();
END//
DELIMITER ;

INSERT INTO courses (id_curso, nombre_curso) VALUES ('0001', 'ETICA PROFESIONAL');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0005', 'TECNICAS DE ESTUDIO E INVESTIGACION');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0006', 'IDIOMA TECNICO 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0008', 'IDIOMA TECNICO 2');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0009', 'IDIOMA TECNICO 3');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0010', 'LOGICA');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0011', 'IDIOMA TECNICO 4');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0014', 'ECONOMIA');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0017', 'AREA SOCIAL HUMANISTICA 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0018', 'FILOSOFIA DE LA CIENCIA');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0019', 'AREA SOCIAL HUMANISTICA 2');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0022', 'PSICOLOGIA INDUSTRIAL');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0027', 'BIOLOGIA');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0028', 'ECOLOGIA');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0030', 'GEOGRAFIA');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0039', 'DEPORTES 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0060', 'TALLER DE SIST DE INF GEOGRAFICA');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0069', 'AREA TECNICA COMPLEMENTARIA 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0073', 'DIBUJO TECNICO MECANICO');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0074', 'DIBUJO CONSTRUCTIVO PARA INGENIERIA');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0080', 'TOPOGRAFIA 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0082', 'TOPOGRAFIA 2');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0084', 'TOPOGRAFIA 3');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0090', 'PROGRAMACION DE COMPUTADORAS 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0092', 'PROGRAMACION DE COMPUTADORAS 2');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0101', 'AREA MATEMATICA BASICA 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0103', 'AREA MATEMATICA BASICA 2');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0107', 'AREA MATEMATICA INTERMEDIA 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0112', 'AREA MATEMATICA INTERMEDIA 2');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0114', 'AREA MATEMATICA INTERMEDIA 3');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0116', 'MATEMATICA APLICADA 3');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0118', 'MATEMATICA APLICADA 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0120', 'MATEMATICA APLICADA 2');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0122', 'MATEMATICA APLICADA 4');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0123', 'MATEMATICA APLICADA 5');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0147', 'FISICA BASICA');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0150', 'FISICA 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0152', 'FISICA 2');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0154', 'FISICA 3');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0156', 'FISICA 4');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0170', 'MECANICA ANALITICA 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0172', 'MECANICA ANALITICA 2');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0173', 'ANALISIS MECANICO');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0196', 'CALIDAD DEL AIRE');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0198', 'CALIDAD DEL AGUA');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0200', 'INGENIERIA ELECTRICA 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0201', 'INSTALACIONES ELECTRICAS (CIVIL)');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0202', 'INGENIERIA ELECTRICA 2');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0204', 'CIRCUITOS ELECTRICOS 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0206', 'CIRCUITOS ELECTRICOS 2');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0208', 'INSTALACIONES ELECTRICAS');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0209', 'INSTALACION DE EQUIPOS ELECTRONICOS');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0210', 'TEORIA ELECTROMAGNETICA 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0211', 'TEORIA ELECTROMAGNETICA 2');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0212', 'CONVERSION DE ENERGIA ELECTROMECANICA 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0213', 'CONVERSION DE ENERGIA ELECTROMECANICA 2');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0214', 'MAQUINAS ELECTRICAS');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0216', 'SUBESTACIONES');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0218', 'LINEAS DE TRANSMISION');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0219', 'TRANSMISION Y DISTRIBUCION');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0220', 'ANALISIS DE SISTEMAS DE POTENCIA 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0221', 'SISTEMAS DE GENERACION');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0222', 'PROTECCION DE SISTEMAS DE POTENCIA');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0224', 'ALTA TENSION');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0230', 'INSTRUMENTACION ELECTRICA');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0232', 'ELECTRONICA 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0233', 'ELECTRONICA APLICADA 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0234', 'ELECTRONICA 4');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0235', 'ROBOTICA');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0236', 'SISTEMAS DE CONTROL 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0238', 'AUTOMATIZACION INDUSTRIAL');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0239', 'ELECTRONICA APLICADA 2');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0240', 'ELECTRONICA 2');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0241', 'RADIOCOMUNICACIONES TERRESTRES');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0242', 'COMUNICACIONES 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0243', 'COMUNICACIONES 4');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0244', 'COMUNICACIONES 2');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0245', 'COMUNICACIONES 3');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0246', 'ELECTRONICA 3');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0248', 'ELECTRONICA 5');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0249', 'ELECTRONICA 6');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0250', 'MECANICA DE FLUIDOS');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0252', 'HIDRAULICA');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0254', 'HIDROLOGIA');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0258', 'MAQUINAS HIDRAULICAS');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0262', 'AGUAS SUBTERRANEAS');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0280', 'INGENIERIA SANITARIA 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0281', 'SISTEMAS OPERATIVOS 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0282', 'INGENIERIA SANITARIA 2');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0283', 'ANALISIS Y DISE\O DE SISTEMAS 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0284', 'SANEAMIENTO AMBIENTAL');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0302', 'RESISTENCIA DE MATERIALES 2');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0307', 'TIPOLOGIA ESTRUCTURAL');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0311', 'ANALISIS ESTRUCTURAL');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0314', 'CONCRETO ARMADO 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0316', 'CONCRETO ARMADO 2');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0318', 'CIMENTACIONES 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0320', 'CIMENTACIONES 2');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0322', 'DISE\O ESTRUCTURAL 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0324', 'DISE\O ESTRUCTURAL 2');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0332', 'PUENTES');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0335', 'GESTION DE DESASTRES');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0346', 'METODOS DE CONSTRUCCION Y SUPERVISION DE OBRAS');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0348', 'QUIMICA GENERAL 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0349', 'QUIMICA PARA INGENIERIA CIVIL');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0352', 'QUIMICA 2');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0354', 'QUIMICA 3');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0358', 'QUIMICA ORGANICA 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0360', 'QUIMICA ORGANICA 2');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0362', 'ANALISIS CUALITATIVO');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0364', 'ANALISIS CUANTITATIVO');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0366', 'ANALISIS INSTRUMENTAL');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0368', 'PRINCIPIOS DE METROLOGIA');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0370', 'QUIMICA AMBIENTAL');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0380', 'FISICO QUIMICA 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0382', 'FISICO QUIMICA 2');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0386', 'LABORATORIO DE FISICO QUIMICA 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0388', 'LABORATORIO DE FISICO QUIMICA 2');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0390', 'TERMODINAMICA 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0392', 'TERMODINAMICA 2');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0394', 'TERMODINAMICA 3');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0396', 'TERMODINAMICA 4');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0398', 'CINETICA DE PROCESOS QUIMICOS');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0409', 'SEPARACION POR MEDIO DE MEMBRANAS SELECTIVAS');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0410', 'BALANCE DE MASA Y ENERGIA');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0412', 'FLUJO DE FLUIDOS');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0414', 'IQ-3 TRANSFERENCIA DE CALOR');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0416', 'IQ-4 TRANSFERENCIA DE MASA');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0418', 'IQ-5 TRANSFERENCIA DE MASA EN UNIDADES CONTINUAS');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0421', 'GESTION TOTAL DE LA CALIDAD');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0423', 'EXTRACCIONES INDUSTRIALES');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0428', 'LABORATORIO DE INGENIERIA QUIMICA 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0430', 'LABORATORIO DE INGENIERIA QUIMICA 2');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0434', 'PROCESOS QUIMICOS INDUSTRIALES');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0436', 'DISE\O DE EQUIPO');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0437', 'CONTROL DE CONTAMINANTES INDUSTRIALES');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0440', 'MICROBIOLOGIA');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0442', 'BIOINGENIERIA 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0450', 'GEOLOGIA');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0452', 'CIENCIA DE LOS MATERIALES');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0453', 'MATERIALES DE CONSTRUCCION 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0454', 'METALURGIA Y METALOGRAFIA');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0455', 'MATERIALES DE CONSTRUCCION 2');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0458', 'MECANICA DE SUELOS 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0460', 'PAVIMENTOS');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0462', 'ELECTRICIDAD Y ELECTRONICA BASICA');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0472', 'TECNOLOGIA DE LOS ALIMENTOS');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0476', 'GEOLOGIA DEL PETROLEO');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0482', 'OPERACIONES Y PROCESOS EN LA INDUSTRIA FARMACEUTICA');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0486', 'DISE\O DE PLANTAS');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0502', 'REFRIGERACION Y AIRE ACONDICIONADO');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0504', 'MOTORES DE COMBUSTION INTERNA');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0506', 'PLANTAS DE VAPOR');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0508', 'MONTAJE Y MANTENIMIENTO DE EQUIPO');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0510', 'INSTALACIONES MECANICAS');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0511', 'MANTENIMIENTO DE HOSPITALES 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0512', 'INSTRUMENTACION MECANICA');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0520', 'PROCESOS DE MANUFACTURA 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0522', 'PROCESOS DE MANUFACTURA 2');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0524', 'DISE\O DE MAQUINAS 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0526', 'DISE\O DE MAQUINAS 2');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0528', 'DISE\O DE MAQUINAS 3');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0530', 'MECANISMOS');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0532', 'VIBRACIONES');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0550', 'VIAS TERRESTRES 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0560', 'VIAS TERRESTRES 2');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0585', 'INGENIERIA DE TRANSITO Y TRANSPORTES');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0601', 'INVESTIGACION DE OPERACIONES I');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0603', 'INVESTIGACION DE OPERACIONES II');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0606', 'ANALISIS DE SISTEMAS INDUSTRIALES');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0608', 'INTROD DE PROYECTOS GERENCIALES');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0610', 'INFORMATICA');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0630', 'INGENIERIA DE LA PRODUCCION');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0632', 'INGENIERIA DE PLANTAS');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0634', 'INGENIERIA DE METODOS');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0636', 'DISE\O PARA LA PRODUCCION');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0637', 'DISEÑO INDUSTRIAL');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0638', 'CONTROLES INDUSTRIALES');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0640', 'CONTROL DE LA PRODUCCION');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0642', 'SEGURIDAD E HIGIENE INDUSTRIAL');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0644', 'INGENIERIA TEXTIL 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0650', 'CONTABILIDAD 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0652', 'CONTABILIDAD 2');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0654', 'CONTABILIDAD 3');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0656', 'ADMINISTRACION DE EMPRESAS 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0657', 'ADMINISTRACION DE EMPRESAS 2');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0658', 'ADMINISTRACION DE PERSONAL');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0660', 'MERCADOTECNIA 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0661', 'MERCADOTECNIA 2');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0662', 'LEGISLACION 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0663', 'LEGISLACION AMBIENTAL 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0664', 'LEGISLACION 2');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0665', 'MICROECONOMIA');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0665', 'MICROECONOMIA');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0666', 'COSTOS PRESUPUESTOS Y AVALUOS');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0667', 'PROGRAMACION COMERCIAL 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0669', 'ECONOMIA INDUSTRIAL');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0687', 'GEOLOGIA ESTRUCTURAL');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0700', 'INGENIERIA ECONOMICA 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0702', 'INGENIERIA ECONOMICA 2');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0704', 'INGENIERIA ECONOMICA 3');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0706', 'PREPARACION Y EVALUACION DE PROYECTOS 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0708', 'PREPARACION Y EVALUACION DE PROYECTOS 2');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0710', 'PLANEAMIENTO');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0712', 'URBANISMO');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0720', 'MODELACION Y SIMULACION 2');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0722', 'TEORIA DE SISTEMAS 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0724', 'TEORIA DE SISTEMAS 2');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0729', 'MODELACION Y SIMULACION 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0732', 'ESTADISTICA 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0734', 'ESTADISTICA 2');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0735', 'AUDITORIA DE PROYECTOS DE SOFTWARE');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0736', 'ANALISIS PROBABILISTICO');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0769', 'INTRODUCCION A LA PROGRAMACION DE COMPUTADORAS');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0770', 'INTRODUCCION A LA PROGRAMACION Y COMPUTACION 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0771', 'INTRODUCCION A LA PROGRAMACION Y COMPUTACION 2');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0772', 'ESTRUCTURAS DE DATOS');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0773', 'MANEJO E IMPLEMENTACION DE ARCHIVOS');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0774', 'SISTEMAS DE BASES DE DATOS 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0775', 'SISTEMAS DE BASES DE DATOS 2');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0777', 'ORGANIZACION DE LENGUAJES Y COMPILADORES 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0778', 'ARQUITECTURA DE COMPUTADORES Y ENSAMBLADORES 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0779', 'ARQUITECTURA DE COMPUTADORES Y ENSAMBLADORES 2');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0780', 'SOFTWARE AVANZADO');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0781', 'ORGANIZACION DE LENGUAJES Y COMPILADORES 2');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0785', 'ANALISIS Y DISE\O DE SISTEMAS 2');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0786', 'SISTEMAS ORGANIZACIONALES Y GERENCIALES 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0787', 'SISTEMAS ORGANIZACIONALES Y GERENCIALES 2');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0788', 'SISTEMAS APLICADOS 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0790', 'EMPRENDEDORES DE NEGOCIOS INFORMATICOS');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0795', 'LOGICA DE SISTEMAS');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0796', 'LENGUAJES FORMALES Y DE PROGRAMACION');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0797', 'SEMINARIO DE SISTEMAS I');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0798', 'SEMINARIO DE SISTEMAS 2');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0799', 'SEMINARIO DE INVESTIGACION');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0960', 'MATEMATICA PARA COMPUTACION 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0962', 'MATEMATICA PARA COMPUTACION 2');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0964', 'ORGANIZACION COMPUTACIONAL');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0968', 'INTELIGENCIA ARTIFICIAL 2');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0969', 'TELECOMUNICACIONES Y REDES LOCALES');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0970', 'REDES DE COMPUTADORAS 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0972', 'INTELIGENCIA ARTIFICIAL 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0975', 'REDES DE COMPUTADORAS 2');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0098', 'PROYECTOS DE COMPUTACION APLICADA A I.E.');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0991', 'LENGUAJES DE PROGRAMACION APLICADOS A I.E.');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('1023', 'DIPLOMADO EN ACONDICIONAMIENTO DEL AGUA EN LA INDUSTRIA');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('1025', 'DIPLOMADO EN ADMINISTRACION DE LA CALIDAD');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('1034', 'DIPLOMADO EN ADMINISTRACION DE LA CALIDAD EN LA INDUSTRIA ALIMENTICIA');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('1035', 'DIPLOMADO EN MATEMATICAS DE INGENIERIA');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('1056', 'DIPLOMADO SEGURIDAD INDUSTRIAL Y SALUD OCUPACIONAL');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('1059', 'DIPLOMADO BUENAS PRACTICAS DE MAN EN LA IND FARMA Y ALIMENTICIA');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('1060', 'DIPLOMADO CADENA DE SUMISTROS');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('1065', 'DIPLOMADO ADMINISTRACION Y COMPETENCIAS');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('1071', 'DIPLOMADO MANTENIMIENTO INDUSTRIAL');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('1074', 'DIPLOMADO EN LIDERAZGO DEL TALENTO HUMANO');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('1076', 'DIPLOMADO EN GESTION GERENCIAL DE OPERACIONES');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('1077', 'DIPLOMADO EN RECURSOS HUMANOS');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('1084', 'DIPLOMADO DE PROPIEDAD INTELECTUAL');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('1088', 'DIPLOMADO REDACCION Y ORTOGRAFIA PARA LA INGENIERIA');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('1090', 'DIPLOMADO ELABORACION, FORMULACION Y EVALUACION DE PROYECTOS DE AGUA POTABLE Y SANEAMIENTO');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('1091', 'DIPLOMADO DESARROLLO DE PRACTICAS EMPRESARIALES');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('2001', 'PRACTICAS FINALES INGENIERIA CIVIL');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('2002', 'PRACTICAS FINALES INGENIERIA QUIMICA');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('2003', 'PRACTICAS FINALES INGENIERIA MECANICA');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('2004', 'PRACTICAS FINALES INGENIERIA ELECTRICA');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('2005', 'PRACTICAS FINALES INGENIERIA INDUSTRIAL');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('2006', 'PRACTICAS FINALES INGENIERIA MECANICA ELECTRICA');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('2007', 'PRACTICAS FINALES INGENIERIA MECANICA INDUSTRIAL');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('2009', 'PRACTICAS FINALES INGENIERIA CIENCIAS Y SISTEMAS');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('2013', 'PRACTICAS FINALES INGENIERIA ELECTRONICA');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('2025', 'PRACTICAS INICIALES');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('2035', 'PRACTICAS FINALES INGENIERIA AMBIENTAL');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('2036', 'PRACTICAS INTERMEDIAS');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('3022', 'PSICOLOGIA INDUSTRIAL (DIPLOMADO)');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('3116', 'MATEMATICA APLICADA 3 (DIPLOMADO)');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('3118', 'MATEMATICA APLICADA 1 (DIPLOMADO)');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('3120', 'MATEMATICA APLICADA 2 (DIPLOMADO)');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('3123', 'MATEMATICA APLICADA 5 (DIPLOMADO)');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('3606', 'ANALISIS DE SISTEMAS INDUSTRIALES (DIPLOMADO)');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('3656', 'ADMINISTRACION DE EMPRESAS 1 (DIPLOMADO)');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('3657', 'ADMINISTRACION DE EMPRESAS 2 (DIPLOMADO)');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('3658', 'ADMINISTRACION DE PERSONAL (DIPLOMADO)');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('3661', 'MERCADOTECNIA 2 (DIPLOMADO');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('3662', 'LEGISLACION 1 (DIPLOMADO)');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('3664', 'LEGISLACION 2 (DIPLOMADO)');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('3669', 'ECONOMIA INDUSTRIAL (DIPLOMADO');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('371', 'PLANEAMIENTO (DIPLOMADO)');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('5003', 'DIBUJO TECNICO');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('5008', 'ARITMETICA');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('5010', 'SEGURIDAD EN LAS OBRAS DE CONSTRUCCION');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('5011', 'FUNDAMENTOS JURIDICOS CONSTITUCIONALES BASICOS DEL DERECHO LABORAL Y NORMAS LABORALES');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('5012', 'COMUNICACION Y REDACCION I');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('7902', 'SEMINARIO DE INVESTIGACION QUIMICA');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('7904', 'SEMINARIO DE INVESTIGACION ELECTRICA');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('7905', 'SEMINARIO DE INVESTIGACION INDUSTRIAL');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('7913', 'SEMINARIO DE INVESTIGACION ELECTRONICA');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('7935', 'SEMINARIO DE INVESTIGACION AMBIENTAL');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('7980', 'INVESTIGACION 1');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('7981', 'SEMINARIO DE INVESTIGACION E.P.S. CIVIL');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('7982', 'SEMINARIO DE INVESTIGACION E.P.S. QUIMICA');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('7983', 'SEMINARIO DE INVESTIGACION E.P.S. MECANICA');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('7984', 'SEMINARIO DE INVESTIGACION E.P.S. ELECTRICA');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('7985', 'SEMINARIO DE INVESTIGACION E.P.S. INDUSTRIAL');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('7986', 'SEMINARIO DE INVESTIGACION E.P.S. MECANICA ELECTRICA');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('7987', 'SEMINARIO DE INVESTIGACION E.P.S. MECANICA INDUSTRIAL');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('7988', 'SEMINARIO DE INVESTIGACION E.P.S. ELECTRONICA');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('7989', 'SEMINARIO DE INVESTIGACION E.P.S. AMBIENTAL');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('7991', 'SEMINARIO DE INVESTIGACION CIVIL');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('7993', 'SEMINARIO DE INVESTIGACION MECANICA');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('7994', 'SEMINARIO DE INVESTIGACION MECANICA ELECTRICA');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('7995', 'SEMINARIO DE INVESTIGACION MECANICA INDUSTRIAL');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('7999', 'SEMINARIO DE INVESTIGACION E.P.S. SISTEMAS');
INSERT INTO courses (id_curso, nombre_curso) VALUES ('0900', 'P.A.P. DE MATEMATICA PARA INGENIERIA');
